name: Run Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install chromium --with-deps

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xvzf allure-2.27.0.tgz -C /opt
          ln -s /opt/allure-2.27.0/bin/allure /usr/local/bin/allure

      - name: Run tests
        run: pytest tests/ -v --alluredir=allure-results

      - name: Generate Allure report
        if: always() # so it'll work when tests fail
        run: allure generate allure-results -o allure-report --clean

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
